name: Deploy to GKE

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation (if used in future)

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker asia-south2-docker.pkg.dev --quiet

      - name: Build and Push Frontend Image
        run: |
          docker build -t asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-frontend:latest ./frontend
          docker push asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-backend:latest ./backend
          docker push asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-backend:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials mern-cluster --region asia-south2

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./manifests/
