name: Deploy MERN App to Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_FRONTEND: asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-frontend
  IMAGE_BACKEND: asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mern-repo/task-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Backend
      run: |
        docker build -t $IMAGE_BACKEND ./backend
        docker push $IMAGE_BACKEND

    - name: Build and Push Frontend
      run: |
        docker build -t $IMAGE_FRONTEND ./frontend
        docker push $IMAGE_FRONTEND

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/backend backend=$IMAGE_BACKEND
        kubectl set image deployment/frontend frontend=$IMAGE_FRONTEND
